import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Upload } from "../components/Upload";
import { ImageContextProvider } from "../context/imageContext";
import { ImagePreview } from "../components/ImagePreview";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>KTP Watermark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <ImageContextProvider>
            <Upload />
            <ImagePreview />
          </ImageContextProvider>
        </div>
      </main>
    </div>
  );
};

export default Home;
