/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from "next";
import Head from "next/head";
import { Upload } from "../components/Upload";
import { ImageContextProvider } from "../context/Image";
import { ImageEditor } from "../components/ImageEditor";
import { Flex, Box, Link, Text } from "@chakra-ui/react";
import { ExternalLinkIcon } from "@chakra-ui/icons";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>tanda-air-ktp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Noto+Serif&family=Space+Mono&display=swap"
          rel="stylesheet"
          crossOrigin="anonymous"
        />
      </Head>

      <div>
        <ImageContextProvider>
          <Flex minH="100vh" align="center" justify="center" m="8">
            <Box>
              <Text fontWeight="bold" fontSize={{ base: "2xl", md: "4xl" }}>
                Beri tanda air di KTP-mu
              </Text>
              <Link
                href="https://github.com/mukhlisakbr/tanda-air-ktp"
                isExternal
              >
                GitHub <ExternalLinkIcon mx="2px" />
              </Link>
              <Upload />
              <ImageEditor />
            </Box>
          </Flex>
        </ImageContextProvider>
      </div>
    </div>
  );
};

export default Home;
