import type { NextPage } from "next";
import Head from "next/head";
import { Upload } from "../components/Upload";
import { ImageContextProvider } from "../context/Image";
import { ImageEditor } from "../components/ImageEditor";
import { Flex, Box, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>tanda-air-ktp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ImageContextProvider>
          <Flex minH="100vh" align="center" justify="center">
            <Box>
              <Text fontSize="4xl">Beri tanda air di KTP-mu</Text>
              <Upload />
              <ImageEditor />
            </Box>
          </Flex>
        </ImageContextProvider>
      </div>
    </div>
  );
};

export default Home;
