import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Upload } from "../components/Upload";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>KTP Watermark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Upload />
          {/* <Image
            src={img}
            alt="Picture of the author"
            width={500}
            height={500}
          /> */}
        </div>
      </main>
    </div>
  );
};

export default Home;
